### ISSUE TITLE
maven plugin testleri 

### ISSUE THREAD

**Issue by cemo** [semcelik/validation-example#3]
Başka pluginlerde nasıl test yazılıyor inceler misin?

**Comment by semcelik** [comment]
test plugin'ini çalıştırdığımda 
java.lang.NoClassDefFoundError: org/apache/maven/execution/MavenExecutionResult
şeklinde hata alıyorum.

Integration testi ve invoker pluginini araştırıyorum şimdi

**Comment by semcelik** [comment]
Cemal Abi, basic bir örnek yollar mısın biraz karışık geldi benim bulduklarım.

**Comment by cemo** [comment]
https://github.com/mojohaus/flatten-maven-plugin/tree/master/src/it

`it` diye bizin olmalı. Buradaki kodlari incele.

**Comment by semcelik** [comment]
bir örnek yaptım.
it klasörü altında iki adet maven projesi oluşturdum.
first-it projesinde subpom isimli plugin oluşturup print isminde goal ekledim, denemelik.
print goal'ü için bir adet dummy unit test oluşturdum çalışıp çalışmadığını görmek için (diğer unit testler de dummy)
first-it projesinde aynı zamanda validator:properties goal'ünü çağırdım first-it projesindeki config.properties dosyasının validation kontrolünü yapıyor.
bir de enforcer plugininin evaluateBeanshell rule'unu kullandım pom dosyalarında. log içinde daha kolay fark ettiğim için.

second-it projesinde ise sadece enforcer plugini çağırdım ayrınca ana pom dosyamda "<preBuildHookScript>script.groovy</preBuildHookScript>" konfigürasyonunu kullandığım için denemelik bir adet groovy dosyası oluşturdum (groovy nedir bilmiyorum 5 dakika internettten syntax'ına bakıp basit bir şey oluşturdum.)

test phase'inde unit testler, integration-test phase'inde hem unit testler hem de invoker plugini çalışıyor. invoker plugin'inin run goal'ünde sadece invoker plugini çalışıyor.

1- integration testinin projenin bütünlüğünü test ettiğini biliyorum (yanlış bilmiyorsam..). Bu projede de alt projeleri de build edip kontrol ettiğine göre ben integration testi mi yazmış oldum basit de olsa?
2- pluginler için unit test yazmaya çalışmıştım dün pek becerememiştim tekrar deneyeyim mi?
3- first-it projesi plugin içeriyor ama build ettiğimde jar dosyasını target\it\first-it\target\ klasörü altına çıkarıyor. bu nedenle plugini çağırdığımda .m2 klasöründeki repomda bulamıyor, haliyle plugin çalışmıyor. Bunun bir yolu var mı?
